TRANSLATIONS = {
    "FR": {
      "home":"Accueil","players":"Joueurs","ranking":"Classement","history":"Historique","rules":"Règles","admin":"Admin","season":"Saison 26/27","tagline":"Discipline aujourd’hui, victoires demain","pot":"Cagnotte totale","paid":"Payé","remaining":"Reste à payer","fines":"Amendes","top":"Top contributeurs","pay":"Payer par Wero","search":"Rechercher un joueur","all":"Tous","locker_room":"Le vestiaire","attackers":"Attaquants","defenders":"Défenseurs","goalies":"Gardiens","back_players":"Retour aux joueurs","player_history":"Historique du joueur","no_fines":"Aucune amende pour le moment.","ranking_title":"Classement 26/27","fine_count":"amendes","all_fines":"Toutes les amendes","statuses":"Statuts","pending":"À payer","appeal":"En appel","cancelled":"Annulé","locker_rules":"Règlement du vestiaire 26/27","rule_note":"Jour de match : montant ×2 · Appel refusé : montant ×2. Les paiements sont validés manuellement.","view_profile":"Voir le profil","admin_area":"Zone administrateur","demo_warning":"Mode démo : les modifications restent dans cette session.","open_demo":"Ouvrir l’admin démo","password":"Mot de passe","login":"Se connecter","wrong_password":"Mot de passe incorrect","add_fine":"Ajouter une amende","payments":"Paiements","player":"Joueur","reason":"Motif","other":"Autre","custom_reason":"Motif personnalisé","base_amount":"Montant de base (€)","match_day":"Jour de match ×2","comment_optional":"Commentaire (optionnel)","final_amount":"Montant final","confirm":"Confirmer","cancel":"Annuler","fine_added":"Amende ajoutée.","save":"Sauver","saved":"Modifiée","appeal_accepted":"Appel accepté","appeal_refused":"Appel refusé ×2","delete":"Supprimer définitivement","amount":"Montant","method":"Méthode","comment":"Commentaire","record_payment":"Enregistrer le paiement","payment_saved":"Paiement enregistré","payment_note":"Les paiements sont imputés au solde global du joueur, des amendes les plus anciennes aux plus récentes.","first_name":"Prénom","last_name":"Nom","number":"Numéro","position":"Poste","add_player":"Ajouter le joueur","active":"Actif","inactive":"Inactif","new_rule":"Nouvelle règle","hungarian_translation":"Traduction hongroise","add":"Ajouter","wero_missing":"QR Wero non configuré. L’administrateur doit ajouter assets/qr/wero.png.","wero_help":"Scannez le QR, indiquez votre nom dans le libellé, puis prévenez l’administrateur. Le paiement sera confirmé manuellement.","demo_mode":"MODE DÉMO"
    },
    "HU": {
      "home":"Kezdőlap","players":"Játékosok","ranking":"Ranglista","history":"Előzmények","rules":"Szabályok","admin":"Admin","season":"26/27-es szezon","tagline":"Fegyelem ma, győzelmek holnap","pot":"Teljes kassza","paid":"Kifizetve","remaining":"Fizetendő","fines":"Bírságok","top":"Legnagyobb hozzájárulók","pay":"Fizetés Weróval","search":"Játékos keresése","all":"Összes","locker_room":"Az öltöző","attackers":"Támadók","defenders":"Védők","goalies":"Kapusok","back_players":"Vissza a játékosokhoz","player_history":"A játékos előzményei","no_fines":"Még nincs bírság.","ranking_title":"26/27-es ranglista","fine_count":"bírság","all_fines":"Összes bírság","statuses":"Állapotok","pending":"Fizetendő","appeal":"Fellebbezés alatt","cancelled":"Törölve","locker_rules":"Öltözői szabályzat 26/27","rule_note":"Meccsnap: összeg ×2 · Elutasított fellebbezés: összeg ×2. A fizetéseket manuálisan igazolják.","view_profile":"Profil megtekintése","admin_area":"Adminisztráció","demo_warning":"Demó mód: a módosítások csak ebben a munkamenetben maradnak meg.","open_demo":"Demó admin megnyitása","password":"Jelszó","login":"Bejelentkezés","wrong_password":"Helytelen jelszó","add_fine":"Bírság hozzáadása","payments":"Fizetések","player":"Játékos","reason":"Indok","other":"Egyéb","custom_reason":"Egyéni indok","base_amount":"Alapösszeg (€)","match_day":"Meccsnap ×2","comment_optional":"Megjegyzés (opcionális)","final_amount":"Végösszeg","confirm":"Megerősítés","cancel":"Mégse","fine_added":"Bírság hozzáadva.","save":"Mentés","saved":"Módosítva","appeal_accepted":"Fellebbezés elfogadva","appeal_refused":"Fellebbezés elutasítva ×2","delete":"Végleges törlés","amount":"Összeg","method":"Fizetési mód","comment":"Megjegyzés","record_payment":"Fizetés rögzítése","payment_saved":"Fizetés rögzítve","payment_note":"A fizetések a játékos legrégebbi nyitott bírságaira kerülnek elszámolásra.","first_name":"Keresztnév","last_name":"Vezetéknév","number":"Mezszám","position":"Poszt","add_player":"Játékos hozzáadása","active":"Aktív","inactive":"Inaktív","new_rule":"Új szabály","hungarian_translation":"Magyar fordítás","add":"Hozzáadás","wero_missing":"A Wero QR-kód nincs beállítva. Az adminisztrátornak hozzá kell adnia: assets/qr/wero.png.","wero_help":"Olvasd be a QR-kódot, írd a neved a közleménybe, majd jelezd az adminnak. A fizetés manuálisan kerül jóváhagyásra.","demo_mode":"DEMÓ MÓD"
    },
}

def t(key, lang="FR"):
    return TRANSLATIONS.get(lang, TRANSLATIONS["FR"]).get(key, key)
